Repository DdNnTt/Chingu-Frontend, pull requests merged in 2025-05, with the labels that each got.

#32 쪽지 리스트, 상세, 쓰기 페이지 생성 및 레이아웃 구성
  .github/workflows/chromatic.yml
  src/app/front/message/detail/page.tsx
  src/app/front/message/list/page.tsx
  src/app/front/message/write/page.tsx
  src/app/front/my-home/friend/page.tsx
  src/components/common/Button.stories.tsx
  src/components/common/Button.tsx
Labels: Priority:medium, Feat, Design

#34 로그인, 회원가입 상대 경로 → 절대 경로 수정
  src/app/front/accout/login/page.tsx
  src/app/front/accout/signup/page.tsx
  src/app/front/intro/page.tsx
Labels: Cleanup, Priority:medium

#38 axios 인스턴스 추가
  package-lock.json
  package.json
  src/libs/axios.ts
Labels: Feat, Priority:low

#40 이메일 인증번호 발송, 요청 API 연결
  src/app/api/auth/email/confirm/route.ts
  src/app/api/auth/email/verify/route.ts
  src/app/api/users/check-nickname/route.ts
  src/app/front/accout/signup/page.tsx
  src/components/common/CheckableInput.tsx
  src/components/common/EmailVerificationInput.tsx
Labels: Front-end, Priority:medium, Feat
