Repository DdNnTt/Chingu-Frontend, pull requests merged in 2025-07, with the labels that each got.

#83 쪽지 보내기 API 연동
  src/app/front/message/list/page.tsx
  src/app/front/my-home/friend/[friendId]/page.tsx
  src/app/front/my-home/page.tsx
  src/components/common/MessageModal.tsx
Labels: Priority:medium, Feat

#85 마이홈 페이지에 내 그룹 목록 API 연동
  src/app/front/my-home/page.tsx
Labels: Priority:medium, Feat

#91 칭구칭구 메인 인트로 디자인 변경
  public/images/friend.png
  src/app/front/intro/page.tsx
  src/styles/globals.css
Labels: Feat, Priority:low

#97 그룹 상세 페이지 수정 및 앨범 보기 페이지 생성
  src/app/api/groups/[groupId]/albums/route.ts
  src/app/front/my-home/group/album/add/page.tsx
  src/app/front/my-home/group/album/albumList/page.tsx
  src/app/front/my-home/group/detail/page.tsx
Labels: Priority:medium, Feat, Design
