Repository DdNnTt/Chingu-Frontend, pull requests merged in 2025-10, with the labels that each got.

#131 나를 맞춰봐 마이홈 UI 변경
  package-lock.json
  package.json
  src/app/admin/member/page.tsx.backup
  src/app/front/game/guess-me/make-quiz/complete/page.tsx
  src/app/front/game/guess-me/make-quiz/page.tsx
  src/app/front/game/guess-me/solve-quiz/page.tsx
  src/app/front/message/detail/MessageDetail.tsx
  src/app/front/my-home/.page.tsx.swp
  src/app/front/my-home/friend-list/page.tsx
  src/app/front/my-home/friend/page.tsx
  src/app/front/my-home/page.tsx
Labels: Priority:medium, Design

#133 이미지 업로드 보안 강화
  public/favicon.png
  src/app/api/groups/[groupId]/albums/route.ts
  src/app/api/users/mypage/edit/route.ts
  src/app/api/users/upload-url/profile/route.ts
  src/app/front/account/login/page.tsx
  src/app/front/my-home/group/album/add/page.tsx
  src/app/front/my-home/group/album/detail/page.tsx
  src/app/front/my-home/page.tsx
  src/app/front/my-page/page.tsx
  src/app/layout.tsx
  src/components/common/CheckableInput.tsx
  src/components/common/Input.tsx
Labels: Fix, Priority:high

#135 프론트 유저 검색 기능 수정
  src/app/api/groups/[groupId]/schedules/add/route.ts
  src/app/front/my-home/group/detail/page.tsx
  src/app/front/my-home/group/schedule/page.tsx
  src/app/front/my-home/page.tsx
  src/app/front/search/SearchUser.tsx
  src/app/layout.tsx
  src/components/common/ScheduleModal.tsx
Labels: Fix, Priority:medium
