Repository DdNnTt/Chingu-Frontend, pull requests merged in 2025-02, with the labels that each got.

#4 ESLint, Prettier, Husky 환경 셋팅
  .eslintrc.json
  .husky/pre-commit
  .prettierignore
  .prettierrc
  package-lock.json
  package.json
Labels: Priority:high, Setting

#6 워크플로우 CI 구현
  .github/workflows/github-actions.yml
  .husky/pre-commit
Labels: Priority:medium, Setting

#10 storybook 기본 셋팅 및 컴포넌트 button, input storybook 적용 완료
  .eslintrc.json
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/app/layout.tsx
  src/components/common/Button.stories.tsx
  src/components/common/Input.stories.tsx
  tailwind.config.ts
Labels: Priority:medium, Feat, Design, Docs, Setting

#12 인트로 페이지 디자인
  src/app/front/intro/page.tsx
  src/styles/globals.css
Labels: Priority:medium, Feat, Design

#14 storybook 배포 기능 추가 및 자동 배포 CI 기능 추가
  .github/workflows/chromatic.yml
  package-lock.json
  package.json
Labels: Feat, Setting, Priority:low

#16 Input, button 컴포넌트 리팩토링
  src/app/front/accout/login/page.tsx
  src/components/common/Button.tsx
  src/components/common/Input.tsx
Labels: Refactor, Priority:high

#18 로그인 페이지 UI 구현 (API 연결 전)
  src/app/front/accout/login/page.tsx
  src/app/front/accout/signup/page.tsx
  src/styles/globals.css
Labels: Feat, Design, Priority:low
